version: 2.1
orbs:
  architect: giantswarm/architect@0.15.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/run-kat-tests:
          name: "test with kat"
          chart: "kong-app"
          ct_config: ".circleci/ct-config.yaml"
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: "package and push kong-app chart"
          requires:
            - "test with kat"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kong-app"
          ct_config: ".circleci/ct-config.yaml"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
