apiVersion: v1
description: The Cloud-Native Ingress and API-management
engine: gotpl
home: https://konghq.com/
icon: https://s.giantswarm.io/app-icons/1/png/kong-app-light.png
maintainers:
- name: hbagdi
  email: harry@konghq.com
- name: rainest
  email: traines@konghq.com
name: kong-app
sources:
- https://raw.githubusercontent.com/giantswarm/kong-app/v[[ .Version ]]/README.md
version: [[ .Version ]]
appVersion: 2.1
