apiVersion: v1
description: The Cloud-Native Ingress and
  Service Mesh for APIs and Microservices
engine: gotpl
home: https://KongHQ.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
name: kong-app
sources:
- https://github.com/Kong/kong
- https://raw.githubusercontent.com/giantswarm/kong-app/v[[ .Version ]]/README.md
version: [[ .Version ]]
appVersion: 2.0.4
